# Generated by Django 3.2.1 on 2021-05-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='default', max_length=45),
            preserve_default=False,
        ),
    ]
